"""add_orders_2

Revision ID: 077732e56030
Revises: 08fd8b9d1f54
Create Date: 2023-06-06 17:55:45.792745

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "077732e56030"
down_revision = "08fd8b9d1f54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("fills", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pair", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trading_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("client_order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transact_time", sa.BIGINT(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("orig_qty", sa.Float(), nullable=False),
        sa.Column("executed_qty", sa.Float(), nullable=True),
        sa.Column("cummulative_quote_qty", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time_in_force", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ord_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("side", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("margin_buy_borrow_amount", sa.Float(), nullable=True),
        sa.Column(
            "margin_buy_borrow_asset", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_isolated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
