"""add loans 3

Revision ID: cf8f1158e840
Revises: 077732e56030
Create Date: 2023-06-10 10:46:20.638235

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf8f1158e840"
down_revision = "077732e56030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loans",
        sa.Column("tran_id", sa.BIGINT(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("trading_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "loan_operation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("loans")
    # ### end Alembic commands ###
